config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-jade-warthog.sh
        container: qc.acc_sloppy-cornflower-frog
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-heliotrope-husky.sh
        container: qc.doc_clammy-champagne-corgi
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cornflower-seahorse.sh
        container: qc.doc_flabby-white-jellyfish
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chestnut-urchin.sh
        container: qc.doc_slimy-olive-tuatara
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-purple-fly.sh
        container: qc.doc_ready-magenta-cassowary
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-persimmon-baboon.sh
        container: qc.lic_geeky-myrtle-lizard
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-orange-tamarin.sh
        container: qc.met_nippy-seashell-beagle
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-rose-peccary.sh
        container: qc.sec_freaky-chartreuse-spaniel
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-taupe-squirrel.sh
        container: qc.sty_pasty-cerise-tamarin
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-copper-otter.sh
        container: qc.sty_bluesy-viridian-dingo
      github.com/SeisSol/SeisSol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-fuchsia-elephant.sh
        container: qc.sty_bumpy-magnolia-falcon
  QC.Uni:
    repos:
      github.com/SeisSol/SeisSol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-buff-crane.sh
        container: qc.uni_nippy-sapphire-markhor
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-mustard-shrew.sh
        container: qc.ver_queasy-aquamarine-yak
timeout: 5400
