config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-indigo-corgi.sh
        container: qc.acc_sleazy-mauve-pinscher
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-asparagus-kudu.sh
        container: qc.doc_craggy-lavender-cassowary
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-red-goose.sh
        container: qc.doc_squirrely-burgundy-giraffe
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-eggplant-ostrich.sh
        container: qc.doc_slaphappy-denim-mist
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-bistre-dingo.sh
        container: qc.doc_chummy-teal-newfoundland
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-scarlet-penguin.sh
        container: qc.lic_droopy-denim-earwig
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-zucchini-barnacle.sh
        container: qc.met_surly-teal-chicken
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-carmine-vole.sh
        container: qc.sec_fuzzy-ultramarine-drever
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-wheat-iguana.sh
        container: qc.sty_zippy-saffron-mau
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ultramarine-macaw.sh
        container: qc.sty_leaky-periwinkle-salamander
      github.com/SeisSol/SeisSol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-myrtle-mule.sh
        container: qc.sty_snazzy-scarlet-urchin
  QC.Uni:
    repos:
      github.com/SeisSol/SeisSol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-coati.sh
        container: qc.uni_gamy-xanthic-stingray
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-pear-monster.sh
        container: qc.ver_seedy-buff-meerkat
timeout: 5400
