config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-silver-cuttlefish.sh
        container: qc.acc_tasty-aqua-forest
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-chartreuse-deer.sh
        container: qc.doc_trippy-green-woodlouse
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-wisteria-ostrich.sh
        container: qc.doc_pokey-rose-clam
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-teal-forest.sh
        container: qc.doc_messy-mauve-emu
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rust-woodlouse.sh
        container: qc.doc_scummy-chocolate-kudu
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-malachite-chinook.sh
        container: qc.lic_tasty-russet-kiwi
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cornflower-buffalo.sh
        container: qc.met_homey-pink-dollar
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-mauve-urchin.sh
        container: qc.sec_slimy-cinnamon-gibbon
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-magenta-turkey.sh
        container: qc.sty_sloppy-thistle-donkey
      github.com/SeisSol/SeisSol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-russet-kudu.sh
        container: qc.sty_ugly-teal-zorse
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-blue-newt.sh
        container: qc.sty_gummy-ivory-okapi
      github.com/SeisSol/SeisSol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-russet-squirt.sh
        container: qc.sty_randy-corn-gibbon
  QC.Uni:
    repos:
      github.com/SeisSol/SeisSol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-purple-hyena.sh
        container: qc.uni_cheeky-cobalt-gorilla
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-jade-pig.sh
        container: qc.ver_sunny-rust-insect
timeout: 5400
